### PR TITLE
Fixed symlink usage

### PR DESCRIPTION
**Pull request by CoolGoose**
Fixed symlink usage and moved the content check at the end to compensate for it.

### CODE REVIEW

**Comment by jasonlewis** [comment]
Could you elaborate a bit on this... I'm not sure I understand what this fix is for.

**Comment by CoolGoose** [comment]
because of the symlinks the exists function would return false. I'll post
my basset config asap so you can see for yourself
On May 22, 2012 3:12 AM, "Jason Lewis" <
reply@reply.github.com>
wrote:

**Comment by jasonlewis** [comment]
Okay cool thanks. I thought I'd implemented it correctly! :( Heh.

**Comment by CoolGoose** [comment]
http://paste.laravel.com/1BG - the bundles.
In config i have 'symlinks' => array('//personal' => '/home/coolgoose/Work/personal') like before.
The thing is this works, even if the exists returns false,

``` php
if($this->group == 'styles')
{
    $contents = Vendor\URIRewriter::rewrite($contents, dirname($this->file), $document_root, $symlinks);
}
```

:)

**Pull request closed without merging**
