### PR TITLE
Added symlink functionality:

### PR DESCRIPTION
**Pull request by CoolGoose**
Eg:

Basset::styles('admin', function($basset)
{
    $basset->directory('public/css/admin', function($basset)
    {
        $basset->add('bootstrap', 'bootstrap.css')
               ->add('admin', 'admin.css')
               ->add('bootstrap-responsive', 'bootstrap-responsive.css');
    });
}, array('symlinks' => array('//personal' => '/home/coolgoose/Work/personal')));

Formatting is a bit off :) can you help me with it ?

### CODE REVIEW

**Comment by CoolGoose** [comment]
@jasonlewis looks good ? :P

**Comment by jasonlewis** [comment]
So your problem was to do with the file being stored in a symlink'd directory?

I'm just wondering if this could be done in the configuration file, but also have a `symlinks` method.

```
Basset::styles('example', function($basset)
{
    $basset->symlink('//example', '/path/to/example');

    // Or as an array.

    $basset->symlink(array(
        '//example' => '/path/to/example'
    ));
});
```

It shouldn't matter where you add them, does that sound reasonable?

**Comment by CoolGoose** [comment]
@jasonlewis  Yap my problem was due to the fact that i had my projects folder symlinked to var/www . 

So you want it in a symlink method (like the dir one) in addition to my changes, or to replace my changes ?

**Comment by jasonlewis** [comment]
Ah I see. Well I was just thinking it could be globally configurable (in the config/basset.php file) but also allow it to be added on runtime with a method. If that sounds okay to you I'll make the appropriate changes. I'll use your code as a reference though. :)

**Comment by CoolGoose** [comment]
Sounds great jason. Let me know if you need any help.

**Comment by jasonlewis** [comment]
I didn't get a chance today to work on it @CoolGoose, I'll get time hopefully after the next 4 days. If you've got something that's working for you at the moment I'd just stick with that for now. There's a few things I'll be implementing in the next release. Shouldn't be too long. Thanks a lot for your work. :)

**Comment by CoolGoose** [comment]
Np ;) Close this so you won't have any pull requests on your mind :P. As a quick note, see if you can disable the profiler automatically when you create basset's routes :)

**Comment by jasonlewis** [comment]
This should be now fixed on the develop branch.

https://github.com/jasonlewis/basset/commit/89a478533d9c3b3edcfd0d685e09b2afed348a2d

**Pull request closed without merging**
