### PR TITLE
Update dependencies to match both Laravel 4 and 4.1

### PR DESCRIPTION
**Pull request by Anahkiasen**

### CODE REVIEW

**Comment by jasonlewis** [comment]
The `~` in this case is basically `4.*` right?

**Comment by crynobone** [comment]
@jasonlewis might be better to have split branch for 4.0 and 4.1 dev.

**Comment by jasonlewis** [comment]
@crynobone Yeah that might be best. Suggestions?

**Comment by Anahkiasen** [comment]
Well Basset really doesn't really on any heavy parts of Laravel, it just hooks into the Service Provider which isn't going to change any time soon, I think it's safe to use like this.

**Pull request closed without merging**
