### PR TITLE
Fix/fsclean glob

### PR DESCRIPTION
**Pull request by ghost**
Check if result of glob is array / not-empty / not === false

### CODE REVIEW

**Comment by codegefluester** [comment]
:+1:

**Comment by jasonlewis** [comment]
According to PHP.net it returns "an empty array if no file matched or FALSE on error." Wouldn't it be better just to ensure that the result is an array, if not, return, otherwise run the loop.

**Comment by vanadium23** [comment]
When this request will be merged, because pull it on every devs comp doesn't have any pleasure)

**Comment by jasonlewis** [comment]
I'm not sure why so many checks are required. Care to fill me in?

**Comment by ghost** [comment]
removed the unnecessary checks. can you pull it ?

**Comment by vanadium23** [comment]
Thanks!

**Pull request merged**
